---
title: "Smart Collector INEDIT"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

# Package for reading InfluxDB
#library(influxdbr)
# install.packages("remotes")
#remotes::install_github("dleutnant/influxdbr")
library(leaflet)
library(tidyverse)
source('R/Places.R')
```

Column {data-width=650}
-----------------------------------------------------------------------

### Deployment of Smart Collectors

```{r}
# 
# iconSet <- awesomeIconList(
#   Home = makeAwesomeIcon(icon = "home", library = "fa", markerColor = 'green'),
#   Education = ?makeAwesomeIcon(icon = "school", library = "fa", markerColor = 'blue'),
#   Association = makeAwesomeIcon(icon = "shop", library = "fa", markerColor = 'grey'),
#   Sport = makeAwesomeIcon(icon = "dumbbell", library = "fa",  markerColor = 'orange')
# )


leaflet(Places) %>%
 addTiles() %>%
 setView(lng = Places$long[8], lat = Places$lat[1], zoom = 18)%>%
   # addAwesomeMarkers(lng = INEDIT$long, lat = INEDIT$lat,
   #                    label = INEDIT$Place,
   #                    popup = INEDIT$Type,
   #                     icon = iconSet
   #    )
   addMarkers(lng = Places$long, lat = Places$lat) %>% 
   #addPopups(lng = INEDIT$long, lat = INEDIT$lat) %>% 
   addScaleBar(position = "bottomleft") 



```

### Recovery profile of the Green Fablab

```{r, fig.width=8, fig.height=6, out.width='90%'}
Recovery %>% 
   mutate(Year= format(Date, "%Y"),
          Month= format(Date, "%B")) %>% 
   select(Year, Month, Quantity) %>% 
   group_by(Year, Month) %>% 
   summarise(Collected = sum(Quantity)) %>% 
   mutate(Month=factor(Month, levels = month.name)) %>% 
   ggplot()+
   aes(x = Month, y = Collected, fill = Year) + 
      geom_bar(stat = "identity") +
   scale_fill_brewer(palette="Set2")+
    labs(title = "Recovery of Plastic of wastes",
       subtitle = "3D Printing Recycled Plastic Demonstrator",
       x = "Months",
       y = "Plastic collected [kilograms]",
       caption = paste("Data Source update by UL on",
                       format(Sys.Date(), "%b/%y"),
                       sep = ":  "
                       )
       )+
  theme_minimal(base_size = 15, base_family = "Palatino") +
   theme(legend.position="bottom")

#ggsave("Results/Recovery.jpg", width = 8, height = 6, dpi = "print")
```



Column {data-width=350}
-----------------------------------------------------------------------

### Recovery per Stakeholder 

```{r, fig.width=9, fig.height=9, out.width='90%'}

data <- 
   Recovery %>% 
   group_by(Type) %>% 
   summarise(Total = sum(Quantity)) 

# Compute percentages
data <- 
   data %>% 
   mutate(fraction = Total / sum(Total))

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(data$Type, ":\n ", data$Total)



# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Type)) +
  geom_rect() +
  geom_text( x=2, aes(y=labelPosition, label=label, color=Type), size=6) + # x here controls label position (inner / outer)
  scale_fill_brewer(palette="Set2") +
  scale_color_brewer(palette="Set2") +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
    labs(title = "Stakeholders type in the Recovery of Plastic of wastes",
       subtitle = "3D Printing Recycled Plastic Demonstrator",
       #x = "Months",
       #y = "Plastic collected [kilograms]",
       caption = paste("Data Source update by UL on",
                       format(Sys.Date(), "%b/%y"),
                       sep = ":  "
                       )
       )+
  theme_void(base_size = 15, base_family = "Palatino") +
   theme(legend.position = "none")  +
   annotate("text", x = 0, y = 0, label = paste("Total recovery: ", paste(sum(data$Total), "kg"), sep = '\n'),
            size=10)

#ggsave("Results/Stakeholder.jpg", width = 9, height = 9, dpi = "print")

```

### Chart C

```{r}

```

